// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://muahvjwdadjfkvokbsay.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im11YWh2andkYWRqZmt2b2tic2F5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3NjM1MTksImV4cCI6MjA2NjMzOTUxOX0.EcTtqTesUBBlfByA4XxlKvBgPsvudRRNVKqHql43-RA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);